### ISSUE TITLE
Implement functionnal tests

### ISSUE THREAD

**Issue by jderusse** [acmephp/symfony-bundle#2]
You can use letsencrypt staging : https://acme-staging.api.letsencrypt.org/directory

**Comment by tgalopin** [comment]
The problem is the same: there are limitations on the number of calls. You can do this, but we will at some point run into the limit and tests won't pass for one week ...

**Comment by jderusse** [comment]
didn't know that... :/

I have to implement a CertificateAuthority then :)

**Comment by jderusse** [comment]
Letsencrypt has already implemented such server (https://github.com/letsencrypt/boulder). 

This is how they use it with Travis https://github.com/letsencrypt/letsencrypt/blob/master/.travis.yml

But it require mariadb + rabbitmq, it might be communicate to bootstrap in dev env. Wonder if I will not implement my own "testAcmeCA"

**Comment by jderusse** [comment]
fixed by #1
