### ISSUE TITLE
check domain format

### ISSUE THREAD

**Issue by jderusse** [acmephp/symfony-bundle#3]
regarding to CA policy, domains format can be restricted : 
    - allow/reject wildcard `/^\*\./`
    - allow/reject puny `/xn--/`
    - allow/reject ip adresse
    - rejecet non fqdn = /^((?!-)[A-Za-z0-9-]{1,63}(?<!-)\.)+[A-Za-z]{2,63}$/

then sanitize
    - encode ascii + lower

**Comment by tgalopin** [comment]
So you think we should check for this validation before starting any request? I think that's a good idea,but we need to be absolutely sure of the rules we put in place.

**Comment by jderusse** [comment]
Those rules come from the python Letsencrypt client.

But you've a point : What if one of the rule changes in the futur (ie: someday, letsencrypt allow Internationalized domain name)
From the other hand, such validation would provide nicer errors messages.
Current message is:
- **for wildcard** `The ACME server returned the error HTTP status code during request to https://acme-v01.api.letsencrypt.org/acme/new-authz (detail: 400 Error creating new authz :: Invalid character in DNS name)`
- **for puny** `The ACME server returned the error HTTP status code during request to https://acme-v01.api.letsencrypt.org/acme/new-authz (detail: 400 Error creating new authz :: Internationalized domain names (starting with xn--) not yet supported`

**Comment by tgalopin** [comment]
Perhaps the best way is, instead of doing or own validation, to catch such specific server messages and improve exceptions for them (and fallback to current system). If the rule change on server side, we still would have a valid exception, just a less friendly one.

**Comment by jderusse** [comment]
Yep, you're right. the best way is to let the CA validate the input. 

Closed in favor of #5
